image: python:3-alpine

stages:
  - Build
  - Deploy

Build:Production:
  image: docker
  stage: Build
  services:
    - docker:dind
  tags:
    - docker
  variables:
    IMAGE_NAME: frontend
    ENV_TAG: production
    DOCKER_FILE: ./Dockerfile
  script: ./scripts/build-image.sh
  only:
    - master

Deploy:Production:
  stage: Deploy
  script:
    - pip3 install jelapi
    - python deploy.py website production
  only:
    - master
