image: node:14
deploy:
  only:
    - master
    - ci-test-deploy
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - apt-get update -y
    - apt-get install sshpass lftp
    - apt-get -y install rsync
    - npm ci
    - npm run build
    - npm run generate
    - sshpass -p $SSH_PASSWORD rsync --progress -avz -e ssh dist/ dregazzoni@toner.o2switch.net:/home/dregazzoni/sites/playground.displaycoding.com


